library(shiny)
library(shinydashboard)

library(tidyverse)
library(ggplot2)
library(dplyr)
US_trend_states_BR <- read.csv("NCHS_-_U.S._and_State_Trends_on_Teen_Births.csv")

```{r}
colnames(US_trend_states_BR)

US_trend_states_BR <- US_trend_states_BR %>%
  mutate(
    StateBirths = as.numeric(as.character(`State.Births`)),
    USBirths = as.numeric(as.character(`U.S..Births`))
  )

US_trend_states_BR <- US_trend_states_BR %>%
  rename(
    StateRate = `StateRate`  
  )

aggregated_data <- US_trend_states_BR %>%
  group_by(State, Year) %>%
  summarise(
    AverageStateRate = round(mean(StateRate, na.rm = TRUE), 2),
    TotalStateBirths = sum(StateBirths, na.rm = TRUE),
    .groups = 'drop'
  ) %>%
  arrange(State, desc(Year)) 

knitr::kable(aggregated_data, caption = "Aggregated Teen Births Data by State and Year")
```

if (!requireNamespace("shinydashboard", quietly = TRUE)) {
  install.packages("shinydashboard")
}



ui <- dashboardPage(
  dashboardHeader(title = "Teen Pregnancy Analysis"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Introduction", tabName = "intro", icon = icon("info-circle")),
      menuItem("Exploration", tabName = "data_explore", icon = icon("dashboard")),
      menuSubItem("Average Birth Rate by State", tabName = "average_state"),
        menuSubItem("U.S. Births Rates Over Year", tabName = "us_br_over_year"),
        menuSubItem("Trends in Rate by State", tabName = "trends_rate_state"),
      menuItem("Insights & Conclusions", tabName = "conclusions", icon = icon("flag-checkered"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "intro",
              fluidPage(
                titlePanel("Teenagers Pregnancy Rate Analysis and Solutions in US"),
                tags$img(src = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM4N6eOa4Q-pwupp8uMwU0kMuRnLuwRxzVOA&s", height = "300px", width = "500px"),
                h3("Introduction"),
                p("Our goal would be aiming on the trends and determinants of teenage pregnancy rates in each state in the US, focusing on teens between the ages of 15 and 19 years old. By discovering and pairing to different abortion laws and educational conditions in each state, the goal is to reveal the correlation between these factors and the rate of teenage pregnancy. As social attitudes toward teen pregnancy become more critical, we believe there is necessary to explore deeper in this social situation. Teenage pregnancy would bring out lots of negative results, for example, affecting teenagers' mental development and physical health etc. We plan to utilize up-to-date and dynamic data from the recent decade to ensure that our research is relevant and current. This approach will allow us to further explore how different laws and educations affect teenage mental and physical health. In addition, we hope the project can highlight broader implications for public health and social policy, providing improvements for the development of targeted interventions and solutions. By identifying the key factors that influence teen pregnancy rates, our project aims call on action for policymakers to develop effective strategies to address this challenging social issue. Overall, our main goal is to provide actionable solutions that could help in reduce the teen pregnancy rates, thus improving and ensuring the well-being of teenagers across the United States."),
                a("Here is the dataset.",
                href = "https://www.cdc.gov/nchs/data-visualization/teen-births/index.htm"),
                h3("Our Research Questions"),
                p("1.How have teenage pregnancy rates changed across different states over approximately the past decade, and what can we tell from these trends?"),
                p("2.What is the relationship between state abortion laws and teenage pregnancy rates from different states?"),
                p("3.How do sex education influences teenage pregnancy rates in different states?")
             )
      ),
      tabItem(tabName = "data_explore",
              fluidPage(
                h1("Let's analysis the data"),
                h3("About this Dataset"),
                p("- We directly found and accessed this dataset can from National Center for Health Statistics, a U.S. federal agency responsible for collecting and analyzing health data to provide statistical information that guides public health and policy decisions."),
                p("- We've found that this dataset was collected by NCHS, which it's the part of the CDC, a principle agency in the US."),
                p("- NCHS collects all the data from a variety of health and demographic surveys, along with vital statistics records such as birth certificates. This collection offers extensive information on birth rates, featuring detailed demographic categories that enable trend analysis over time based on race, age group, and Hispanic origin."),
                p("- We believe that their purpose of collecting these teen birth rate data is for monitoring and assessing the teens' health trends to inform public health policy and plans. This dataset would help to evaluate the effectiveness of health interventions for reducing teen pregnancies, also and can influence educational programs and resource allocation for family planning and sex education."),
                h3("Our Implications"),
                p("We think all the results we could get by analyzing this dataset could assist technologists in developing data-driven solutions, such as using big data analysis and AI technology to predict the trends in teenage pregnancy rates and provide more accurate support for policymakers. In addition, technologists can develop online platforms or social media tools to provide teenage health counseling and support services and promote teenage health education and awareness. Secondly, designers can design and improve teenage health education publicity materials according to the research results, making them more attractive and easy to understand, and increasing the participation and acceptance of adolescents. In addition, designers can work with educational institutions and community organizations to develop innovative educational games, apps, or virtual reality experiences that stimulate youth interest and engagement in health issues, thereby promoting an understanding of sex education. Also, the research results could provide important references for developing more direct and efficient policy measures to reduce teenage pregnancy rates and ensure the teenage health. For example, the government can adjust the content and scope of youth sex education courses, increase the popularity and accessibility of family planning services, and formulate stricter policies for teen childbirth.")
              )
      ),
      tabItem(tabName = "average_state",
              fluidPage(
                h1("Average Rate"),
                h3("Average Pregnancy Rate By State"),
                titlePanel("Average Teenage Pregnancy Rates"),
                selectInput("selectState", "Select State:", 
                choices = c("All States" = "All", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"), 
                selected = "All States", 
                multiple = TRUE),
    actionButton("updatePlot", "Update Plot"),
                plotOutput("avgRatesPlot"),
                h3("Summary for the graph"),
                p("- We've chose a bar chart to do this visualization for the average teen birth rates per state because it is particularly effective for comparing categorical data. Each bar represents a state, allowing for straightforward comparisons of their average rates. This visualization is excellent for assessing and comparing the magnitude of teen birth rates across different states at a glance. The orientation and length of the bars make it easy to identify which states have higher or lower averages, highlighting areas that might require more focused interventions or further study. By using distinct colors for each state and rotating the x-axis labels, the chart ensures clarity and readability, enhancing the viewer's ability to digest and interpret the data efficiently. ")
              )
      ),
      tabItem(tabName = "us_br_over_year",
              fluidPage(
              h1("U.S. Birth Rates Over the Years"),
              h3("Explore how birth rates have changed in the U.S. over the years."),
              sliderInput("yearRange", "Select Year Range:", 
                min = 1990, max = 2020, 
                value = c(1990, 2020), step = 1),
                plotOutput("usBirthRatePlot"),
                h3("Summary for the graph"),
                p("- We decided to choose the line and point plot for visualizing the U.S. birth rate over the years primarily because it could effectively and clearly illustrate the trends over time. Line and point plots are excellent for time series data, allowing clear visualization of changes in the birth rate—whether it's rising, declining, or remaining stable. This type of plot provides a continuous view of data, highlighting relationships and movements over the years, which is crucial for understanding demographic dynamics. It can showcase the trends, detect volatility, and identify anomalies, offering a comprehensive overview of how external factors might influence birth rates.")
              )
      ),
      tabItem(tabName = "trends_rate_state",
              fluidPage(
                h1("Trends in Rates by State"),
                h3("Trends in Teenage Pregnancy Rates by State"),
                selectInput("stateInput", "Select a State:", choices = c("All States" = "All", "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming")),
                plotOutput("pregnancyTrendsPlot"),
                h3("Summary for the graph"),
                p("-  We believe this line plot would be an ideal for visualizing the trends in teen birth rates by state over time, due to its ability to clearly show changes through connected data points for each state. By incorporating different colors for each state, the plot facilitates easy comparisons, allowing observers to quickly discern which states have higher or lower rates and how these rates evolve relative to each other. This visualization is particularly valuable for identifying trends, fluctuations, and the impacts of different state policies or healthcare access on teen birth rates.")
                # Add more elements as needed
              )
      ),
      tabItem(tabName = "conclusions",
              fluidPage(
                h1("Conclusions"),
                p("Based on our analysis of teenage pregnancy, we identified key determinants that influence teenage pregnancy rates among teenagers. In order to mitigate this social issue, we propose several solutions to lower teenage pregnancy rate."),
                h2("Possible effective solutions include:"),
                p("1 . Provide in-depth and proper sexual education in the schools which includes how to use contraception to prevent pregnancy, how and when to use contraception to prevent sexually transmitted diseases, the significance of sexual consent, etc. Students should learn from the lessons in a way that when they start having sexual relationships they should take responsible and wise sexual decisions. In other words, proper sex education can help teenagers to take safer and responsible sexual decisions."),
                p("2. Improve access to information on contraception. Provide free or reasonably priced contraceptive means – including information – from schools, community clinics, and online forums. Access counseling: making counseling services by professionals available to support young people when they need someone to talk to."),
                p("3. Innovate discourses in family bases, not just in School but between parents and children to increase the boldness of their sex education and communication.By establishing an information-based group that allows all the members of the community to be involved in activities and workshops that work as a prevention of teenage pregnancy."),
                p("4. Create and implement policies that support the health and rights of adolescents: ensure quality and coverage for sex education programs in all schools; in legislation, ensure that legally competent adolescents’ privacy rights are protected when accessing contraception and counseling services.")
              )
      )
    )
  )
)

server <- function(input, output, session) {
  data <- reactive({
    req(read_csv("NCHS_-_U.S._and_State_Trends_on_Teen_Births.csv"))
  })

  observe({
    updateSelectInput(session, "selectState", choices = c("All" = "All", unique(data()$State)))
    updateSelectInput(session, "stateInput", choices = c("All" = "All", unique(data()$State)))
  })
  
  output$pregnancyTrendsPlot <- renderPlot({
    df <- req(data())
    if (input$stateInput != "All") {
      df <- df[df$State == input$stateInput, ]
    }
    ggplot(df, aes(x = Year, y = `State Rate`, color = State)) +
      geom_line() +
      labs(title = paste("Trends in Teenage Pregnancy Rates by State:", input$stateInput),
           x = "Year", y = "Teenage Pregnancy Rate") +
      theme_minimal()
  })

  average_rates <- reactive({
    df <- req(data())
    if (input$selectState != "All") {
      df <- df %>% filter(State %in% input$selectState)
    }
    df %>%
      group_by(State) %>%
      summarise(AverageRate = mean(`State Rate`, na.rm = TRUE))
  })

  observeEvent(input$updatePlot, {
    output$avgRatesPlot <- renderPlot({
      df_avg <- req(average_rates())
      ggplot(df_avg, aes(x = reorder(State, -AverageRate), y = AverageRate, fill = State)) +
        geom_bar(stat = "identity") +
        labs(title = "Average Teenage Pregnancy Rates by State", x = "State", y = "Average Pregnancy Rate") +
        theme_minimal() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1))
    })
  })
  output$usBirthRatePlot <- renderPlot({
    df <- data()
    # Filter data based on the selected year range from the slider
    filtered_df <- df %>% filter(Year >= input$yearRange[1], Year <= input$yearRange[2])
    ggplot(filtered_df, aes(x = Year, y = `U.S. Birth Rate`)) +
      geom_line() +  # Line plot
      geom_point() + # Add points
      labs(title = "U.S. Birth Rate Over the Years", x = "Year", y = "Birth Rate (per 1,000 people)") +
      theme_minimal()
  })
}

shinyApp(ui = ui, server = server)

